version: '3.7'

services:
  crud.usuarios:
    image: spakov/crud:dev
    container_name: crud-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5000:5000"
    networks:
      - globalnet

  dockersqlserver:
    image: spakov/banco_crud:dev
    container_name: sql-server-linux
    restart: always
    ports:
      - "1435:1433"
    networks:
      - globalnet

networks:
  globalnet: {}